### PR TITLE
#83 - Create lesson container

### LINKED ISSUE #77: (SP:2) Implement view for Lesson
Blocked by #7 

## Description

The objective is to introduce a detailed view for existing lessons within our lesson management system, enhancing the overall user experience by allowing users to view lesson details seamlessly. A significant part of this functionality includes enabling users to redirect to the lesson editing page by clicking on the lesson title. This feature aims to streamline the process of viewing and editing lessons, making it more intuitive and efficient.

### Implement View Logic for Current Lesson

- **Lesson Selection:**
  - In the lesson management interface, each lesson listed should be clickable, specifically the lesson title. When a user clicks on a title, they should be redirected to the view page for that specific lesson

- **Lesson Detail View:**
   - Implement a component or a page layout that displays the details of the selected lesson. This view should at least include the lesson `title` and `description`, presented in a clear and readable format.

- **Edit Redirection:**
   - Ensure that the title of the lesson in the view acts as a link or button that redirects users to the `/edit-lesson/:lessonId` route, where `/:lessonId` is the unique identifier of the lesson being viewed. The redirection should lead to the editing interface  

- **Testing:**
   - Verify that clicking on a lesson title redirects to the correct editing page, with the route properly including the lesson's unique ID.
   - Ensure that this new view integrates seamlessly with the existing lesson management system and the edit functionality, without introducing regressions or bugs.

### LINKED ISSUE #78: (SP:2) Implement Edit for Lessons
Blocked by #7 

## Description

Implement the ability to edit existing lessons through the UI. This feature will be accessible via an "Edit" option within a menu (indicated by three dots) associated with each lesson in the table. Selecting this option will navigate the user to a dedicated edit page, where they can modify the lesson's title and description.

### Implement Edit Logic for Current Lesson
When you create the table, clicking on the three dots selects and creates logic for `Edit`.

Edit Option

- [ ] **New Route:**
   - Selecting the `Edit` option navigates the user to a new route `/edit-lesson/:lessonId`, where `/:lessonId` is the unique identifier of the selected lesson. This route will display a form pre-filled with the lesson's existing title and description for editing.
   - Example route: `/my-resources/edit-lesson/6574b5f32b3d9ee9382a4cc1`

- **Form Fields:**
  - [ ] **Title Field:**
    - Allows the user to modify the lesson title. This should be a text input field pre-filled with the current title.
  - [ ] **Description:**
    - User can edit the description for the current lesson.

- **Action Buttons Below:**
  - [ ] `Save:`
    - Saves the modifications made to the lesson and updates the database. Upon successful save, the user should receive feedback, and the UI should reflect the changes immediately.
  - [ ] `Cancel:`
    - Discards any changes and redirects the user back to the `/my-resources` page.

Action Buttons

### Additional Information
- After clicking on the three dots and selecting the `Edit` button, the user should be directed to the edit page with pre-filled information for the selected lesson.

### LINKED ISSUE #79: (SP:2) Implement 'New lesson'
Blocked By #7 

## Description

The objective of this task is to enhance our lesson management system by introducing a feature that allows users to create new lessons. This involves adding a 'New Lesson' button to the designated container, establishing a new route for lesson creation, and implementing a form with title and description fields, along with 'Save' and 'Cancel' actions.

### Implement:

- [ ] **New Lesson Button:**
   - Place a button labeled 'New Lesson' above the main container, as indicated in the provided mockup. This button should be visually consistent with the application's design language.

Image

- [ ] **New Route Creation:**
   - Implement a new route `/new-lesson` that is triggered upon clicking the 'New Lesson' button. This route should lead to a form where users can input details for creating a new lesson.

- **Form Fields:**
  - [ ] **Title Field:**
    - Include a field for entering the lesson title. This field is mandatory.
  - [ ] **Description:**
    - Provide a text area for the lesson description, allowing for more detailed information about the lesson to be entered.

  - **Action Buttons Below:**
     - [ ] **Save:**
       - On click, this button should validate the input fields and save the new lesson information to the database, subsequently refreshing the lesson table to display the newly created lesson.
     - [ ] **Cancel:**
       - This button should discard any input and redirect the user back to the root `/my-resources` page.

New Lesson Form

- [ ] **Testing:**
   - Write unit tests covering the new functionality, including route navigation, form submission, and action button behavior.
   - Ensure integration tests validate the successful creation of a lesson and its appearance in the lesson table.

### LINKED ISSUE #82: (SP:2) Implement Delete for Lessons
Blocked by #7 

## Description

We need to enhance our lesson management feature by introducing the ability to delete lessons directly from the UI. This functionality will be accessible through an interactive button found within a menu (represented by 3 dots) associated with each lesson item. Upon clicking this button, the system should prompt the user for confirmation before proceeding to delete the lesson. This feature is crucial for maintaining an up-to-date and relevant lesson repository.

## Requirements:

- **Menu Activation:**
  - Users should be able to click on a visual indicator (3 dots) associated with each lesson to reveal available actions.

- **Delete Option:**
   - Among the available actions, a `Delete` button should be clearly visible and intuitive to use.

- **Confirmation Prompt:**
   - Upon selecting the `Delete` option, display a confirmation dialog to prevent accidental deletions. This dialog should detail the action's permanence and require explicit user approval to proceed.

- **Deletion and Feedback:**
   - After user confirmation, the system should delete the current lesson and provide immediate visual feedback, such as a success notification and the removal of the lesson from the list.

## Technical Implementation:

- **UI Components:**
   - Utilize existing design components for the menu and confirmation dialog, ensuring consistency with the application's design language.

- **Backend Integration:**
   - Leverage the `deleteLesson` function from our `ResourceService` for backend integration, ensuring the lesson is permanently removed from the database.

- **Error Handling:**
   - Implement robust error handling to manage potential deletion failures, providing clear user feedback in such cases.

- **State Management:**
   - Ensure the UI reflects the deletion immediately by updating the state to remove the deleted lesson from the visible list without requiring a page reload.

- **Testing:**
   - Write tests covering the new delete functionality, including user interaction flow and state management after deletion.
   - Ensure tests validate the successful deletion process, error handling, and user feedback mechanisms.

## Additional information:

- After clicking on 3 dots and selecting the `Delete` button, the current lesson should be deleted.

Image

### LINKED ISSUE #83: (SP:2) Implement LessonContainer
## Description

The goal of this task is to develop the `LessonContainer` component, a fundamental feature in our application that will serve as the primary interface for managing lessons. This component should provide functionalities for displaying lessons, adding new lessons, editing existing lessons, and integrating with other established components and services.

## Requirements:

- **Structure:**
  - The `LessonContainer` should follow the design patterns and code structure demonstrated in the `Question` and `Categories` components as examples.
  - Utilize Material-UI's `Box` component to wrap the entire container for consistent styling.

- **Functionality:**
   - **AddResourceWithInput:** Integrate the `AddResourceWithInput` component to enable adding new lessons.
   - **MyResourcesTable:** Utilize the `MyResourcesTable` component for displaying the list of lessons. Adjust columns and data handling as necessary to fit the lesson context.
   - **Routing:** Add a new path to the application's router for navigating to the `LessonContainer`.

- **Data Handling and Services:**
   - Implement fetching, deleting, and searching functionalities using the `ResourceService`. Handle these operations with appropriate callbacks and error handling.
   - Use mocked data `{ count: 1, items: [] }` for initial development and testing, ensuring the component can handle dynamic content updates.

- **Tests:**
   - Write tests for the `LessonContainer` to validate its functionality, including integration points with other components and services.
   - Tests should cover user interactions, state management, and integration with the backend services (using mocked data).

### PR DESCRIPTION
**Pull request by Yurii-04**
https://github.com/user-attachments/assets/52abba35-19b0-4f5e-bdc0-f38c47756ea9

### CODE REVIEW

**Review by petro97 — APPROVED** [review]

**Review by Annaivv — APPROVED** [review]

**Review by k7bart — APPROVED** [review]

File: src/containers/my-resources/lessons-container/LessonsContainer.tsx [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+  })
+
+  const deleteLesson = useCallback(
+    (id?: string) => ResourceService.deleteLesson(id ?? ''),
+    []
+  )
+
+  const editLesson = (id?: string) => {
+    navigate(createUrlPath(authRoutes.myResources.editLesson.path, id))
+  }
```
Comment (nrevutska) [inline src/containers/my-resources/lessons-container/LessonsContainer.tsx]: why previous function is wrapped in useCallback and this one isn't?

**Review by nrevutska — APPROVED** [review]

File: src/containers/my-resources/lessons-container/LessonsContainer.tsx (hunk 1 above)
Comment (Yurii-04) [reply src/containers/my-resources/lessons-container/LessonsContainer.tsx]: updated, thanks
